#!/bin/bash
set -e

echo "\
  ######################################################################
  running 02 check-workstation
  ######################################################################"

# Does the plan file exist?
if [ ! -f /root/code/terraform/HashiCatPlan.tfplan ]; then
  fail-message "Could not find the plan file. Did you run 'terraform plan "HashiCatPlan.tfplan"'?" 
fi

# Does a state file exist?
if [ ! -f /root/code/terraform/terraform.tfstate ]; then
  fail-message "Could not find the state file. Did you run 'terraform apply "HashiCatPlan.tfplan"'?"
fi