#!/bin/bash
set -e

echo "\
  ######################################################################
  running 02 setup-workstation
  ######################################################################"

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Clear commands from previous challenge & setup
: > /root/.bash_history

exit 0